[Delivery]
    [Delivery.GRPC]
        port = "50001"
    [Delivery.HTTP]
        port = "80"

[ProductRecom]
    rootURL = "http://localhost:80"

[FeatureFlag]
    isMultiAffinityIncludeGender = true
    isMultiAffinityIncludeUser = true