build:
	go build ./cmd/recom-engine && \
	go build ./cmd/perso-engine

buildrecom:
	go build ./cmd/recom-engine

buildperso:
	go build ./cmd/perso-engine

test:
	go test ./cmd/recom-engine && \
	go test ./cmd/perso-engine