// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product-recom.proto

package recomengine

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetMultiProductRecomRequest struct {
	UserID               int64    `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Limit                int32    `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMultiProductRecomRequest) Reset()         { *m = GetMultiProductRecomRequest{} }
func (m *GetMultiProductRecomRequest) String() string { return proto.CompactTextString(m) }
func (*GetMultiProductRecomRequest) ProtoMessage()    {}
func (*GetMultiProductRecomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_recom_ff5a6320cfd9c573, []int{0}
}
func (m *GetMultiProductRecomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultiProductRecomRequest.Unmarshal(m, b)
}
func (m *GetMultiProductRecomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultiProductRecomRequest.Marshal(b, m, deterministic)
}
func (dst *GetMultiProductRecomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultiProductRecomRequest.Merge(dst, src)
}
func (m *GetMultiProductRecomRequest) XXX_Size() int {
	return xxx_messageInfo_GetMultiProductRecomRequest.Size(m)
}
func (m *GetMultiProductRecomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultiProductRecomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultiProductRecomRequest proto.InternalMessageInfo

func (m *GetMultiProductRecomRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetMultiProductRecomRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetMultiProductRecomResponse struct {
	Data                 []*ProductRecom   `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	Meta                 *ProductRecomMeta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *GetMultiProductRecomResponse) Reset()         { *m = GetMultiProductRecomResponse{} }
func (m *GetMultiProductRecomResponse) String() string { return proto.CompactTextString(m) }
func (*GetMultiProductRecomResponse) ProtoMessage()    {}
func (*GetMultiProductRecomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_recom_ff5a6320cfd9c573, []int{1}
}
func (m *GetMultiProductRecomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMultiProductRecomResponse.Unmarshal(m, b)
}
func (m *GetMultiProductRecomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMultiProductRecomResponse.Marshal(b, m, deterministic)
}
func (dst *GetMultiProductRecomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMultiProductRecomResponse.Merge(dst, src)
}
func (m *GetMultiProductRecomResponse) XXX_Size() int {
	return xxx_messageInfo_GetMultiProductRecomResponse.Size(m)
}
func (m *GetMultiProductRecomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMultiProductRecomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMultiProductRecomResponse proto.InternalMessageInfo

func (m *GetMultiProductRecomResponse) GetData() []*ProductRecom {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetMultiProductRecomResponse) GetMeta() *ProductRecomMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ProductRecomMeta struct {
	OverallAffinities    string   `protobuf:"bytes,1,opt,name=overallAffinities" json:"overallAffinities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductRecomMeta) Reset()         { *m = ProductRecomMeta{} }
func (m *ProductRecomMeta) String() string { return proto.CompactTextString(m) }
func (*ProductRecomMeta) ProtoMessage()    {}
func (*ProductRecomMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_recom_ff5a6320cfd9c573, []int{2}
}
func (m *ProductRecomMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRecomMeta.Unmarshal(m, b)
}
func (m *ProductRecomMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRecomMeta.Marshal(b, m, deterministic)
}
func (dst *ProductRecomMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRecomMeta.Merge(dst, src)
}
func (m *ProductRecomMeta) XXX_Size() int {
	return xxx_messageInfo_ProductRecomMeta.Size(m)
}
func (m *ProductRecomMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRecomMeta.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRecomMeta proto.InternalMessageInfo

func (m *ProductRecomMeta) GetOverallAffinities() string {
	if m != nil {
		return m.OverallAffinities
	}
	return ""
}

type ProductRecom struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Price                int64    `protobuf:"varint,2,opt,name=price" json:"price,omitempty"`
	ShopId               int64    `protobuf:"varint,3,opt,name=shop_id,json=shopId" json:"shop_id,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created" json:"created,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	Name                 string   `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Images               []string `protobuf:"bytes,7,rep,name=images" json:"images,omitempty"`
	Affinity             float32  `protobuf:"fixed32,8,opt,name=affinity" json:"affinity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProductRecom) Reset()         { *m = ProductRecom{} }
func (m *ProductRecom) String() string { return proto.CompactTextString(m) }
func (*ProductRecom) ProtoMessage()    {}
func (*ProductRecom) Descriptor() ([]byte, []int) {
	return fileDescriptor_product_recom_ff5a6320cfd9c573, []int{3}
}
func (m *ProductRecom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProductRecom.Unmarshal(m, b)
}
func (m *ProductRecom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProductRecom.Marshal(b, m, deterministic)
}
func (dst *ProductRecom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProductRecom.Merge(dst, src)
}
func (m *ProductRecom) XXX_Size() int {
	return xxx_messageInfo_ProductRecom.Size(m)
}
func (m *ProductRecom) XXX_DiscardUnknown() {
	xxx_messageInfo_ProductRecom.DiscardUnknown(m)
}

var xxx_messageInfo_ProductRecom proto.InternalMessageInfo

func (m *ProductRecom) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ProductRecom) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *ProductRecom) GetShopId() int64 {
	if m != nil {
		return m.ShopId
	}
	return 0
}

func (m *ProductRecom) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ProductRecom) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProductRecom) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductRecom) GetImages() []string {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *ProductRecom) GetAffinity() float32 {
	if m != nil {
		return m.Affinity
	}
	return 0
}

func init() {
	proto.RegisterType((*GetMultiProductRecomRequest)(nil), "recomengine.GetMultiProductRecomRequest")
	proto.RegisterType((*GetMultiProductRecomResponse)(nil), "recomengine.GetMultiProductRecomResponse")
	proto.RegisterType((*ProductRecomMeta)(nil), "recomengine.productRecomMeta")
	proto.RegisterType((*ProductRecom)(nil), "recomengine.productRecom")
}

func init() { proto.RegisterFile("product-recom.proto", fileDescriptor_product_recom_ff5a6320cfd9c573) }

var fileDescriptor_product_recom_ff5a6320cfd9c573 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xdb, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xd9, 0x43, 0x4f, 0x53, 0x91, 0x3a, 0x8a, 0xc6, 0x13, 0x2c, 0x7b, 0xb5, 0x17, 0xb6,
	0x60, 0x7d, 0x01, 0x05, 0x41, 0x8a, 0x14, 0x24, 0x2f, 0x20, 0x71, 0x33, 0xad, 0x81, 0xdd, 0xcd,
	0x9a, 0x64, 0x05, 0xef, 0x7c, 0x35, 0xdf, 0x4c, 0x36, 0x5b, 0xa5, 0x78, 0xb8, 0x9b, 0x2f, 0xff,
	0x9f, 0xc9, 0x3f, 0x19, 0xd8, 0xaf, 0x8d, 0x96, 0x4d, 0xee, 0xa6, 0x86, 0x72, 0x5d, 0xce, 0x6a,
	0xa3, 0x9d, 0xc6, 0xb1, 0x07, 0xaa, 0xd6, 0xaa, 0xa2, 0xf4, 0x1e, 0x4e, 0xef, 0xc8, 0x2d, 0x9b,
	0xc2, 0xa9, 0x87, 0xce, 0xcb, 0x5b, 0x95, 0xd3, 0x4b, 0x43, 0xd6, 0xe1, 0x21, 0xf4, 0x1b, 0x4b,
	0x66, 0x71, 0xcb, 0x82, 0x24, 0xc8, 0x22, 0xbe, 0x21, 0x3c, 0x80, 0x5e, 0xa1, 0x4a, 0xe5, 0x58,
	0x98, 0x04, 0x59, 0x8f, 0x77, 0x90, 0xbe, 0x07, 0x70, 0xf6, 0x77, 0x37, 0x5b, 0xeb, 0xca, 0x12,
	0x4e, 0x21, 0x96, 0xc2, 0x09, 0x16, 0x24, 0x51, 0x36, 0x9e, 0x1f, 0xcf, 0xb6, 0x92, 0xcc, 0xea,
	0xed, 0x0b, 0xde, 0x86, 0x97, 0x10, 0x97, 0xe4, 0x84, 0x7f, 0x64, 0x3c, 0x3f, 0xff, 0xd7, 0xbe,
	0x24, 0x27, 0xb8, 0xb7, 0xa6, 0xd7, 0x30, 0xf9, 0xa9, 0xe0, 0x05, 0xec, 0xe9, 0x57, 0x32, 0xa2,
	0x28, 0x6e, 0x56, 0x2b, 0x55, 0x29, 0xa7, 0xc8, 0xfa, 0x79, 0x46, 0xfc, 0xb7, 0x90, 0x7e, 0x04,
	0xb0, 0xb3, 0xdd, 0x02, 0x77, 0x21, 0x54, 0x72, 0x33, 0x7f, 0xa8, 0x64, 0x3b, 0x7b, 0x6d, 0x54,
	0x4e, 0x3e, 0x56, 0xc4, 0x3b, 0xc0, 0x23, 0x18, 0xd8, 0x67, 0x5d, 0x3f, 0x2a, 0xc9, 0xa2, 0xee,
	0xab, 0x5a, 0x5c, 0x48, 0x64, 0x30, 0xc8, 0x0d, 0x09, 0x47, 0x92, 0xc5, 0x5e, 0xf8, 0x42, 0x9c,
	0x40, 0xd4, 0x98, 0x82, 0xf5, 0x7c, 0x92, 0xb6, 0x44, 0x84, 0xb8, 0x12, 0x25, 0xb1, 0xbe, 0x3f,
	0xf2, 0x75, 0xbb, 0x02, 0x55, 0x8a, 0x35, 0x59, 0x36, 0x48, 0xa2, 0x6c, 0xc4, 0x37, 0x84, 0x27,
	0x30, 0x14, 0x5d, 0xea, 0x37, 0x36, 0x4c, 0x82, 0x2c, 0xe4, 0xdf, 0xfc, 0xd4, 0xf7, 0x9b, 0xbe,
	0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x13, 0xc9, 0x2c, 0x81, 0x00, 0x02, 0x00, 0x00,
}
